[tool.cibuildwheel]
skip = ["*musllinux*", "*pp*win*", "pp*manylinux*"]

[build-system]
requires = ["setuptools", "numpy", "pyqt5"]
build-backend = "setuptools.build_meta"

[tool.pylint.MASTER]
extension-pkg-whitelist = "PyQt5"
