package:
  name: elongation_simulators
  version: 1.0

source:
  git_url: ssh://heday@192.168.122.1:/Projects/Gillespie_Cpp/.git #[win]
  git_depth: 1 #[win]
  path: /home/heday/Projects/Gillespie_Cpp/ #[not win]

requirements:
  build:
    - git
    - python #[not win]
    - numpy x.x
    - setuptools
    - cmake #[not win]
    - pytest
    - libgcc-ng #[not win]
    - libstdcxx-ng #[not win]
##    - {{compiler('cxx')}} #[win]
##  features:
##    - vc19
    
    
  run:
    - python
    - numpy >=1.1
    - libgcc-ng #[not win]
    - libstdcxx-ng #[not win]



about:
  home:
