package:
  name: elongation_simulators
  version: 1.0

source:
#  git_rev: HEAD
#  git_url: "git://heday@192.168.122.1/Projects/Gillespie-Cpp/"
  path: /home/heday/Projects/Gillespie_Cpp/

requirements:
  build:
    - git
    - python
    - numpy x.x
    - setuptools
    - cmake 
    - pytest
    - libgcc-ng
    - libstdcxx-ng
    
    
  run:
    - python
    - numpy >=1.1
    - libgcc-ng
    - libstdcxx-ng



about:
  home:
