package:
  name: elongation_simulators
  version: 1.0

source:
  git_url: ssh://heday@192.168.122.1:/Projects/Gillespie_Cpp/.git
  git_depth: 1
  path: /home/heday/Projects/Gillespie_Cpp/ #[not win]

requirements:
  build:
    - git
    - python #[not win]
    - numpy x.x
    - setuptools
    - cmake 
    - pytest
    - libgcc-ng #[not win]
    - libstdcxx-ng #[not win]
    
    
  run:
    - python
    - numpy >=1.1
    - libgcc-ng #[not win]
    - libstdcxx-ng #[not win]



about:
  home:
