package:
  name: elongation_simulators
  version: 0.1

source:
  git_url: ssh://heday@192.168.122.1:/mnt/Projects/Gillespie_Cpp/.git #[win]
  git_depth: 1 #[win]
  path: /home/heday/Projects/Gillespie_Cpp/ #[not win]

requirements:
  build:
    - git
    - python #[not win]
    - numpy x.x
    - setuptools
    - cmake #[not win]
    - pytest
    - libgcc-ng #[not win]
    - libstdcxx-ng #[not win]
    - {{compiler('cxx')}} #[win]
#  features:
#    - vc19
    
    
  run:
    - python
    - numpy >=1.1
    - libgcc-ng #[not win]
    - libstdcxx-ng #[not win]
    - pyqt
    - biopython
    # - vs2015_runtime


about:
  home: https://github.com/fheday/elongation_simulator
  license: MIT
  summary: 'Simulators for elongation and ribosome reactions'

