name: build_conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: 'installers/anaconda/elongation_simulator/'
        #AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: ['win-64', 'win-32']
        override: true
        dry_run: true

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl
