on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: conda-incubator/setup-miniconda@v3
      with:
        conda-solver: "classic"
        auto-update-conda: true
        conda-remove-defaults: true
        python-version: ${{ matrix.python-version }}
    - name: get release version
      shell: pwsh
      run: set p/ VERSION=<version.txt 
    - name: install pybind11
      shell: pwsh
      run:  conda install conda-forge::pybind11
    - name: create sdist
      shell: pwsh
      run: python setup.py sdist
    - name: Conda install build-tools
      shell: bash -el {0}
      run: conda install -y conda-build
    - name: install greyskull
      shell: pwsh
      run: conda install -c conda-forge greyskull
    - name: generate recipe
      shell: pwsh
      run: grayskull pypi dist/elongation_simulator-$VERSION.tar.gz
    - name: build package
      shell: pwsh
      run: conda build installers/anaconda/elongation_simulator/meta.yaml
