on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["3.11", "3.12"]
    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: create sdist
      shell: pwsh
      run: python setup.py sdist
    - name: Conda install build-tools
      shell: bash -el {0}
      run: conda install -y conda-build grayskull
    - name: generate recipe
      shell: pwsh
      run: grayskull pypi dist/elongation_simulator-*
    -name: build package
      shell: pwsh
      run: conda build elongation_simulator
