name: Build distribution

on: [push, pull_request]

jobs:
  test:
    runs-on: "ubuntu-latest", "windows-latest", "macos-latest"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install build dependencies
        run: python -m pip install build wheel pybind11 numpy

      - name: Build distributions
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel

