name: Build distribution

on: [push, pull_request]

jobs:
  ubuntu-build:
    matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: ['3.7', '3.8', '3.9' ]

      - name: Install build dependencies
        run: python -m pip install build wheel pybind11 numpy

      - name: Build distributions
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel
