name: Build distribution

on: [push, pull_request]


jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install build dependencies
        run: python -m pip install build wheel pybind11 numpy

      - name: Build distributions
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel

  Windows:
    runs-on: windows-latest"
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install build dependencies
        run: python -m pip install build wheel pybind11 numpy

      - name: Build distributions
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel
